### ISSUE TITLE
Need help in integrating RubberBand.

### ISSUE THREAD

**Issue by iamvikashh** [devingryu/RubberBandAndroidExample#1]
Hello there, i am trying to build rubberband base android app for one of my use case. I am bit new to native code in android.sorry if i am being silly.
I have tried looking for its android support but i couldn't find any proper docs for it. since you have already used in the past. can you pls give some steps or link to any article or any kind of help.

Thanks

**Comment by devingryu** [comment]
The author of RubberBand has not, and will not, provide any specific guidance on Android intergration. What I referred to was the actual code of 'sonic' implementation of Exoplayer library. 

However, if you're familiar with JNI, using the library on Android shouldn't be too different from using it in C. The library provides C header, so you can call library functions directly using JNI.
Even if you're not very familiar with JNI, I think you should be able to use RubberBand on Android with my ExoPlayer implementation as long as you know how to build the library.

For building the library, I remember that the author of the RubberBand provided build guide for Android in [README](https://github.com/breakfastquay/rubberband/tree/cc937ebe655fc3c902ad0bc5cb63ce4e782720ee). Now it doesn't exist, but you can find them in commit history. 
However, the build script(`Android.mk`) is pretty old, so you might want to use meson build system if it doesn't work. 'FluidSynth' library uses meson build for [Android glib building](https://github.com/FluidSynth/fluidsynth/blob/master/.azure/azure-pipelines-android.yml), so you may refer to it if you want to write cross-platform build config for Android.

If you have any other questions, feel free to ask.

**Comment by iamvikashh** [comment]
Thank you for your detailed response. I plan to try building your project since it appears straightforward. However, it seems that Rubberband has undergone significant changes since your project was created. When I attempted to build your project using the latest version of Rubberband, I noticed that many files have been refactored and relocated to different directories. While exploring the Rubberband library, I came across the `RubberBandSingle.cpp` file, which seems to simplify the build process. I modified your `android.mk` file accordingly. I'm not entirely sure if the changes are correct, but it compiled successfully. Here’s the `android.mk` file:

```makefile
LOCAL_PATH := $(call my-dir)
RUBBERBAND_SRC_PATH := $(LOCAL_PATH)/..

include $(CLEAR_VARS)

LOCAL_MODULE := rubberband

RUBBERBAND_JNI_FILES := \
	$(RUBBERBAND_SRC_PATH)/src/jni/RubberBandStretcherJNI.cpp

# Using the single-file build option
LOCAL_SRC_FILES := $(RUBBERBAND_SRC_PATH)/single/RubberBandSingle.cpp

# Specify the include directories
LOCAL_C_INCLUDES := \
   $(RUBBERBAND_JNI_FILES) \
   $(RUBBERBAND_SRC_PATH)/single

# Set the C++ standard to C++11 or later
LOCAL_CPPFLAGS := -std=c++11

# Enable exceptions
LOCAL_CPPFLAGS += -fexceptions

# Link against the C++ shared library (you may also use libc++_static for a static link)
LOCAL_LDLIBS := -lc++_shared

include $(BUILD_SHARED_LIBRARY)
```
Hoping for your insights on this.

**Comment by devingryu** [comment]
I found that Rubberband still provides `Android.mk` in `/otherbuilds` directory. [Link](https://github.com/breakfastquay/rubberband/blob/default/otherbuilds/Android.mk)
You may try with this file I think?

**Comment by iamvikashh** [comment]
Hey, thanks a lot for your help! I was able to use your code successfully. The only change I made was to my `Android.mk` file(Pasted in above comment), which gave me the working `.so` files. Then, I used the CMake file to compile the `rubberbandstretcherjni.cpp` file with my build. I kept the rest of your Java code, and it's working great. Thanks again for your assistance!

**Comment by devingryu** [comment]
I'm glad that it worked well!
